-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 18:36:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movies-ecf` ;

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies-ecf` DEFAULT CHARACTER SET utf8mb4 ;
USE `movies-ecf` ;

-- -----------------------------------------------------
-- Table `movies-ecf`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-ecf`.`categories` ;

CREATE TABLE IF NOT EXISTS `movies-ecf`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `movies-ecf`.`release_years`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-ecf`.`release_years` ;

CREATE TABLE IF NOT EXISTS `movies-ecf`.`release_years` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `release_year` YEAR(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `movies-ecf`.`directors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-ecf`.`directors` ;

CREATE TABLE IF NOT EXISTS `movies-ecf`.`directors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `director_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `movies-ecf`.`infos_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-ecf`.`infos_movies` ;

CREATE TABLE IF NOT EXISTS `movies-ecf`.`infos_movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `release_years_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_infos_movies_release_years_idx` (`release_years_id` ASC) VISIBLE,
  CONSTRAINT `fk_infos_movies_release_years`
    FOREIGN KEY (`release_years_id`)
    REFERENCES `movies-ecf`.`release_years` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `movies-ecf`.`categories_has_infos_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-ecf`.`categories_has_infos_movies` ;

CREATE TABLE IF NOT EXISTS `movies-ecf`.`categories_has_infos_movies` (
  `categories_id` INT NOT NULL,
  `infos_movies_id` INT NOT NULL,
  PRIMARY KEY (`categories_id`, `infos_movies_id`),
  INDEX `fk_categories_has_infos_movies_infos_movies1_idx` (`infos_movies_id` ASC) VISIBLE,
  INDEX `fk_categories_has_infos_movies_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_has_infos_movies_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `movies-ecf`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_infos_movies_infos_movies1`
    FOREIGN KEY (`infos_movies_id`)
    REFERENCES `movies-ecf`.`infos_movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `movies-ecf`.`directors_has_infos_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-ecf`.`directors_has_infos_movies` ;

CREATE TABLE IF NOT EXISTS `movies-ecf`.`directors_has_infos_movies` (
  `directors_id` INT NOT NULL,
  `infos_movies_id` INT NOT NULL,
  PRIMARY KEY (`directors_id`, `infos_movies_id`),
  INDEX `fk_directors_has_infos_movies_infos_movies1_idx` (`infos_movies_id` ASC) VISIBLE,
  INDEX `fk_directors_has_infos_movies_directors1_idx` (`directors_id` ASC) VISIBLE,
  CONSTRAINT `fk_directors_has_infos_movies_directors1`
    FOREIGN KEY (`directors_id`)
    REFERENCES `movies-ecf`.`directors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_directors_has_infos_movies_infos_movies1`
    FOREIGN KEY (`infos_movies_id`)
    REFERENCES `movies-ecf`.`infos_movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
